# Generated by Django 5.0.3 on 2024-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_comment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(default="no title", max_length=50),
            preserve_default=False,
        ),
    ]
